# Generated by Django 3.1.3 on 2021-02-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='extern_id',
            new_name='external_id',
        ),
    ]
