# Generated by Django 3.1.3 on 2021-02-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20210220_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albums',
            new_name='album',
        ),
    ]
